#cloud-config
system_info:
  default_user:
    name: ${username}
    lock_passwd: True
    gecos: SANSForensics
    groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash