#cloud-config
system_info:
  default_user:
    name: ${username}
    lock_passwd: True
    gecos: DefaultUser
    groups:
      [
        adm,
        audio,
        cdrom,
        dialout,
        dip,
        floppy,
        lxd,
        netdev,
        plugdev,
        sudo,
        video,
      ]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
autoinstall:
  version: 1
  apt:
    geoip: true
    disable_components: []
    preserve_sources_list: false
    primary:
      - arches: [amd64, i386]
        uri: http://us.archive.ubuntu.com/ubuntu
      - arches: [default]
        uri: http://ports.ubuntu.com/ubuntu-ports
  locale: en_US
  early-commands:
    - systemctl mask systemd-networkd-wait-online.service
  keyboard:
    layout: us
  identity:
    hostname: ${hostname}
    username: ${username}
    password: ${password}
  ssh:
    install-server: true
    allow-pw: yes
  packages:
    - openssh-server
    - open-vm-tools
    - cloud-init
    - whois
    - zsh
    - wget
    - tasksel
    - ubuntu-desktop
  source:
    id: ubuntu-server-minimal
  user-data:
    disable_root: false
    timezone: UTC
    write_files:
      - path: /etc/gdm3/custom.conf
        content: |
          [daemon]
          AutomaticLoginEnable = true
          AutomaticLogin = ${username}

          [security]

          [xdmcp]

          [chooser]

          [debug]
      - path: /etc/ssh/sshd_config.d/port.conf
        content: |
          Port 2222
    runcmd:
      - systemctl restart ssh.socket
